### ISSUE TITLE
Read comments about last years app

### ISSUE THREAD

**Issue by tovesson** [careerfairsystems/arkad-app#137]
Read the following comments about last years app and fair and see if there are some useful comments for us.

[Enkätresultat-student.docx](https://github.com/careerfairsystems/arkad-app-2018/files/2536017/Enkatresultat-student.docx)
[kommentarer-till-infokanaler.xlsx](https://github.com/careerfairsystems/arkad-app-2018/files/2536018/kommentarer-till-infokanaler.xlsx)

**Comment by liljagustav** [comment]
Större delen av kommentarerna från förra årets app handlade om att det inte fanns tillgång till en karta så användarna hade svårt att hitta till företagen. Det var även en del som klagade på att appen krashade mycket.

Punkter som kan förbättras

- Filtrera på vart företagen har olika kontor eller vart dem befinner sig
- Kunna se företag som är favoritmarkerade i kartan

Slutsats
De flesta klagomål som människor hade förra året har vi fått med i årets app. Funktionerna som jag nämnde ovan är inget krav utan bara saker som har nämnts till mig när folk har provat appen.
