### ISSUE TITLE
Update the map

### ISSUE THREAD

**Issue by arpi09** [careerfairsystems/arkad-app#204]
Uppdatera kartan med de nya byggnaderna som kanske kommer att läggas till.

**Comment by arpi09** [comment]
Update the map with the new building(s) which might be added later.

**Comment by Jaholl** [comment]
Are there any changes and if so, what are these changes?

**Comment by Alexander-Mjoberg** [comment]
There's gonna be changes. The booth areas will mostly be same, there a few changes. However this year companies will be sorted into different "branscher", for instance Data/IT and IT Consulting will be on SC bottom floor. The premise and art directors will make new maps to reflect this that we can import them, they will try to colorise in a way that makes it easy to see what branches are in what building.

**Comment by Alexander-Mjoberg** [comment]
3/6 done
remaining: MA2, SC2, Kårhuset
