### ISSUE TITLE
Change API url when fetching companies (BACKEND)

### ISSUE THREAD

**Issue by arpi09** [careerfairsystems/arkad-app#212]

**Comment by arpi09** [comment]
Can't fix the problem where I get "Unauthorized" when trying to fetch companies with the new url.

**Comment by Alexander-Mjoberg** [comment]
Good that we have an issue for this now. 
The new URL should be https://p18.jexpo.se/arkad/exhibitors?getAttributes=true&filter=["workspace:2019","published:true"]
If you put this in a browser or App it should return an empty result. Final registration isn't done and hence companies aren't published.
You can still access all the companies for this year in Jexpo by using the above link and changing published:undefined
Hope this solves the problem. Publishing should happen sometime in september I think.

**Comment by Alexander-Mjoberg** [comment]
This is basically sorted, we just need to have a short discussion about #379 first, then I need to inform PG before closing
