### ISSUE TITLE
Buttons/Labels

### ISSUE THREAD

**Issue by Jaholl** [careerfairsystems/arkad-app#240]
All buttons and labels will be made to have an icon + text

**Comment by Jaholl** [comment]
Done all but the 3 dots in company and the FAQ, need feedback on this, gets done on thursday hopefully

**Comment by arpi09** [comment]
Do you have a branch for this?

**Comment by Jaholl** [comment]
yes, branch is called buttons/labels

**Comment by arpi09** [comment]
Don't think it is pushed to remote
