### ISSUE TITLE
links as buttons

### ISSUE THREAD

**Issue by Jaholl** [careerfairsystems/arkad-app#241]
Make all links as a button (make a component, might allready exist)

**Comment by arpi09** [comment]
You should not write the link as button text. I think we should have a call to action as text in the buttons. For example the button in "Need an account?" which links to the mail, should have a "Send mail" as text. And the button which tells you where to get more info should maybe have the text "Click here for info". We need call to actions

**Comment by arpi09** [comment]
Don't know if you missed adding buttons in the "help" section when a company is logged in

**Comment by Jaholl** [comment]
the written text in a button is easy to change, and the help i had missed
