### ISSUE TITLE
Implement JWT in API

### ISSUE THREAD

**Issue by arpi09** [careerfairsystems/arkad-app#272]
Some of the API requests that are implemented need to send a JWT to be able to fetch data properly. The JWT should be added in the header, see below.

fetch('/user/data', {
  method: 'GET',
  headers: {
    'Authorization': 'Bearer' + authToken
  }
})
.then(res => res.json())
.then(data => { console.log(data) })
.catch(err => { console.log(err) })

**Comment by Alexander-Mjoberg** [comment]
We already have asynch storage as it's required for react-native permissions library, so maybe this could be useful?
https://medium.com/@njwest/building-a-react-native-jwt-client-api-requests-and-asyncstorage-d1a20ab60cf4
