### ISSUE TITLE
Confirm that company logos work

### ISSUE THREAD

**Issue by tovesson** [careerfairsystems/arkad-app#47]
Found a company logo that did not load (Ecolean). Seems like the URL to the vector works but not the .png thumbnail.

Currently the companies that has issues:
Consafe - hade rätt fil.
Ecolean - har också rätt fil.
John Svensson Bygg saknar url helt. - ingen bild.
LTH studie o karriär - ett textdokument.
Patent o registreringsverket - hade rätt fil.
TrueSec - hade rätt fil.
Yaskawa Nordic AB saknar url helt. - ingen fil.

Seem like there's trouble with the API. The companies affected has three exported thumnails, small, medium, large but the working ones only has two -> small, large.

**Comment by liljagustav** [comment]
John Svensson Bygg - saknar logga
Yaskawa Nordic AB - saknar logga
